-- ─────────────────────────────────────────────────────────────────────────
-- Migration: add program_id FK to events + enable Realtime on profiles
-- Run this in your Supabase SQL editor
-- ─────────────────────────────────────────────────────────────────────────

-- 1. Add program_id column to events (FK to programs table)
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS program_id BIGINT REFERENCES programs(id) ON DELETE SET NULL;

-- 2. Add has_payment column if it doesn't exist yet
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS has_payment BOOLEAN DEFAULT FALSE;

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS payment_amount NUMERIC(10,2);

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS payment_description TEXT;

-- 3. Add created_at to profiles if missing
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- 4. Enable Realtime on profiles so role/status changes propagate instantly
-- (Run in Supabase Dashboard → Database → Replication → enable profiles table)
-- Or via SQL:
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime CASCADE;
  CREATE PUBLICATION supabase_realtime FOR TABLE
    profiles, events, event_photos, announcements, rehearsals, programs, places;
COMMIT;

-- 5. Allow admins to update ANY profile (needed for role/status toggling)
DROP POLICY IF EXISTS "Admins can update any profile" ON profiles;
CREATE POLICY "Admins can update any profile" ON profiles
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 6. Ensure event_photos table exists (safe re-run)
CREATE TABLE IF NOT EXISTS event_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  uploader_id UUID REFERENCES profiles(id),
  image_data TEXT NOT NULL,
  caption TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE event_photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can view event photos" ON event_photos;
CREATE POLICY "Everyone can view event photos" ON event_photos FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can upload photos" ON event_photos;
CREATE POLICY "Authenticated users can upload photos" ON event_photos FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Uploader or admin can delete photos" ON event_photos;
CREATE POLICY "Uploader or admin can delete photos" ON event_photos FOR DELETE USING (
  auth.uid() = uploader_id OR
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
