-- ─────────────────────────────────────────────────────────────────────────
-- Migration v2: program_id en events + event_photos + Realtime + RLS
-- NOTA: en esta base de datos events.id y programs.id son UUID
-- ─────────────────────────────────────────────────────────────────────────

-- 1. Columna program_id en events (FK → programs.id UUID)
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS program_id UUID REFERENCES programs(id) ON DELETE SET NULL;

-- 2. Columnas de pago (si no existen)
ALTER TABLE events ADD COLUMN IF NOT EXISTS has_payment         BOOLEAN       DEFAULT FALSE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS payment_amount      NUMERIC(10,2);
ALTER TABLE events ADD COLUMN IF NOT EXISTS payment_description TEXT;

-- 3. created_at en profiles (si no existe)
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE
  DEFAULT timezone('utc'::text, now());

-- 4. Política: admins pueden editar cualquier perfil
DROP POLICY IF EXISTS "Admins can update any profile" ON profiles;
CREATE POLICY "Admins can update any profile" ON profiles
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 5. Tabla event_photos (event_id UUID porque events.id es UUID)
CREATE TABLE IF NOT EXISTS event_photos (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id    UUID REFERENCES events(id) ON DELETE CASCADE,
  uploader_id UUID REFERENCES profiles(id),
  image_data  TEXT NOT NULL,
  caption     TEXT,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE event_photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can view event photos"        ON event_photos;
DROP POLICY IF EXISTS "Authenticated users can upload photos" ON event_photos;
DROP POLICY IF EXISTS "Uploader or admin can delete photos"   ON event_photos;

CREATE POLICY "Everyone can view event photos"
  ON event_photos FOR SELECT USING (true);

CREATE POLICY "Authenticated users can upload photos"
  ON event_photos FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Uploader or admin can delete photos"
  ON event_photos FOR DELETE USING (
    auth.uid() = uploader_id OR
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 6. Activar Realtime en profiles
ALTER PUBLICATION supabase_realtime ADD TABLE profiles;
