-- Supabase Setup Script for Poetry Club App

-- 1. Create Profiles table (extends AUTH users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE,
  username TEXT UNIQUE,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  full_name TEXT,
  avatar_url TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (id)
);

-- 2. Create Poetries table (zona de poesías)
CREATE TABLE poetries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  author_id UUID REFERENCES profiles(id),
  source_url TEXT, -- For photo/document URL if stored
  is_digitized BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Events table (agendar poesías)
CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT,
  poetries TEXT, -- List of poetries/dramas
  programs TEXT, -- Detailed schedule
  map_url TEXT, -- URL for map embed or link
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by UUID REFERENCES profiles(id)
);

-- 3. New table: Event Participants
CREATE TABLE event_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  UNIQUE(event_id, profile_id)
);

-- 3. Create Places table (lugares a donde tenemos que ir)
CREATE TABLE places (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Announcements table (zona de anuncios)
CREATE TABLE announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT,
  type TEXT CHECK (type IN ('poetry', 'outing', 'general')),
  related_id BIGINT, -- ID of the poetry or event
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Rehearsals table (ensayos)
CREATE TABLE rehearsals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  rehearsal_date TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE places ENABLE ROW LEVEL SECURITY;
ALTER TABLE poetries ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE rehearsals ENABLE ROW LEVEL SECURITY;

-- 5. Policies
-- Profiles: Users can see all profiles, but only update their own
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Events: Everyone can read, only admins can write
CREATE POLICY "Everyone can view events" ON events FOR SELECT USING (true);
CREATE POLICY "Admins can manage events" ON events FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Places: Everyone can read, only admins can write
CREATE POLICY "Everyone can view places" ON places FOR SELECT USING (true);
CREATE POLICY "Admins can manage places" ON places FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Poetries: Everyone can read, anyone can insert (to digitalize), but only owner/admin can delete
CREATE POLICY "Everyone can view poetries" ON poetries FOR SELECT USING (true);
CREATE POLICY "Anyone can insert poetries" ON poetries FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Owner or admin can manage poetries" ON poetries FOR ALL USING (
  auth.uid() = author_id OR 
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Announcements: Everyone can read, only system/admin can write
CREATE POLICY "Everyone can view announcements" ON announcements FOR SELECT USING (true);
CREATE POLICY "Admins can manage announcements" ON announcements FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Rehearsals: Everyone can read, only admins can manage
CREATE POLICY "Everyone can view rehearsals" ON rehearsals FOR SELECT USING (true);
CREATE POLICY "Admins can manage rehearsals" ON rehearsals FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 6. Trigger for new user profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, avatar_url)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ─────────────────────────────────────────────────────────────────
-- 7. Event Photos table (galería de fotos por evento)
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE event_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  uploader_id UUID REFERENCES profiles(id),
  image_data TEXT NOT NULL,   -- Base64 encoded image
  caption TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE event_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Everyone can view event photos" ON event_photos FOR SELECT USING (true);
CREATE POLICY "Authenticated users can upload photos" ON event_photos FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Uploader or admin can delete photos" ON event_photos FOR DELETE USING (
  auth.uid() = uploader_id OR
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ─────────────────────────────────────────────────────────────────
-- 8. Programs table (archivo de programas del grupo)
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  event_name TEXT,            -- Optional: name of the church/event
  author_id UUID REFERENCES profiles(id),
  is_digitized BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE programs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Everyone can view programs" ON programs FOR SELECT USING (true);
CREATE POLICY "Anyone can insert programs" ON programs FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Owner or admin can manage programs" ON programs FOR ALL USING (
  auth.uid() = author_id OR
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

